      </td>
    </tr>
    <tr>
        <td colspan="3" class="mainfoot">
            <table>
                <tr>
                    <td>&nbsp;</td>
                    <td class="footer"><img src="images/TempusPageBottom.gif" alt="Tempus" /></td>
                    <td class="footer">Visual DataFlex 2008 14.0<br />Tempus Remote Access System<br />Copyright: T.W. Boynton 2008</td>
                </tr>
            </table>
        </td>
    </tr>
</table>